### ISSUE TITLE
部分文字显示不全 怎么解决？

### ISSUE THREAD

**Issue by 1617634** [gjTool/pdfh5#1]
部分文字显示不全 怎么解决？

**Comment by gjTool** [comment]
请贴关键代码，以及效果图

**Comment by 1617634** [comment]
@gjTool 


http://www.gjtool.cn/pdfh5/pdf.html?file=http://yofishdk-api-collect-test.youyuwo.com/yofishdk-static/20181204000001cgnHGDihNfSFDn9FQ61h.pdf

http://yofishdk-api-collect-test.youyuwo.com/yofishdk-static/20181204000001cgnHGDihNfSFDn9FQ61h.pdf
部分中文显示不了

**Comment by gjTool** [comment]
修复了，你下最新版的

**Comment by 1617634** [comment]
@gjTool 好的 我试试

**Comment by Pankzou** [comment]
![image](https://user-images.githubusercontent.com/31275493/49857776-50105b00-fe2e-11e8-910e-077c2095767c.png)
