### ISSUE TITLE
onError事件无效

### ISSUE THREAD

**Issue by caifeile** [gjTool/pdfh5#11]
` 		pdfh5.on("start",function(str){
 			console.log("onStart");
 		});
 		pdfh5.on("complete",function(str){
 			console.log("onComplete");
 		});
 		pdfh5.on("error",function(str){
 			console.log("onError");
 		});
 		pdfh5.on("success",function(str){
 			console.log("onSuccess");
 		});`
onError 和 onSuccess事件是这样写么？
onSuccess可用，onError事件无效(故意把pdf的路径写错)

**Comment by gjTool** [comment]
> ` pdfh5.on("start",function(str){ console.log("onStart"); }); pdfh5.on("complete",function(str){ console.log("onComplete"); }); pdfh5.on("error",function(str){ console.log("onError"); }); pdfh5.on("success",function(str){ console.log("onSuccess"); });`
> onError 和 onSuccess事件是这样写么？
> onSuccess可用，onError事件无效(故意把pdf的路径写错)

是这样写的。感谢提出bug。现已修复
