### ISSUE TITLE
添加水印功能-使用canvas文字方法绘制水印

### ISSUE THREAD

**Issue by zouxiong1991** [gjTool/pdfh5#110]
前面版本绘制水印的功能都是使用img的方法，需要提前准备图片展示。是否后续版本增加直接文本展示的水印，根据不同的使用人，传入不同的文字，从而展示不同的水印。不需要在准备图片，只需传入文字就可以了。

**Comment by guandaxia** [comment]
我也想问这个问题，可否支持文字版本的水印
