### ISSUE TITLE
你好,请教一下,怎么禁止移动端手势捏合缩放?

### ISSUE THREAD

**Issue by mtr4020** [gjTool/pdfh5#13]

**Comment by gjTool** [comment]
这个功能没有，你可以去源码里加，很简单的

**Comment by mtr4020** [comment]
能大概给我说一下改哪里嘛,我是做后端的,不是很懂,如果你没时间的话就算了,你写的这个很好,感谢!

**Comment by gjTool** [comment]
![image](https://user-images.githubusercontent.com/36074298/55766624-108a1080-5aa8-11e9-9124-c58396b4b9ab.png)
在pdfh5.js里，这个位置，你加个变量做开关，这里就是初始化手势缩放的。有空我会改下代码。不过现在项目很忙，没时间

**Comment by mtr4020** [comment]
好的,非常感谢!
