### ISSUE TITLE
你好，請問可以像PDF.js 載入base64 格式嗎？

### ISSUE THREAD

**Issue by nathan1658** [gjTool/pdfh5#16]
比如像這樣的：

var pdfData = 'xxxxxxxx';
PDFViewerApplication.open(pdfData);

**Comment by nathan1658** [comment]
function getDoc(data) {
                if (self.pdfLoaded) {
                    return;
                }                            
                pdfjsLib.getDocument({data: pdfData}).then(function(pdf) {
                    if (self.pdfLoaded) {
                        return;
                    }

稍稍修改了這一段就可以了

**Comment by gjTool** [comment]
现在新版本也支持配置data了
