### ISSUE TITLE
android手机上pdf放大后拖动卡顿

### ISSUE THREAD

**Issue by sjqnice** [gjTool/pdfh5#2]

**Comment by gjTool** [comment]
> _No description provided._

这个涉及到现在安卓系统内置的webview浏览器对H5的支持，以及安卓webview本身的性能。目前我是没有办法解决的，我只能建议说你可以试着修改手势拖动那部分源码看看。

**Comment by sjqnice** [comment]
> > _No description provided._
> 
> 这个涉及到现在安卓系统内置的webview浏览器对H5的支持，以及安卓webview本身的性能。目前我是没有办法解决的，我只能建议说你可以试着修改手势拖动那部分源码看看。

谢谢回复  建议把手机端和pc端分开处理，因为手机端的性能没有pc强大，加载pdf速度有点慢，个人建议，仅供参考
