### ISSUE TITLE
带有电子签章的pdf文件，签章不显示

### ISSUE THREAD

**Issue by czh378762** [gjTool/pdfh5#20]
我预览那种带有签章的pdf文件，发现签章不显示。然后，我百度搜索预览签章的pdf，很多回答都是说注释掉pdf.worker.js里面的一段代码，就可以了，默认是不显示签章的。

![image](https://user-images.githubusercontent.com/23158695/61935743-bc0a9280-afbd-11e9-84b4-e23a0664cf53.png)

然后，我去从你github上clone下来的pdf.worker.js文件找这段代码，发现你的那个文件没有这段代码，我又从官网下载下来最新的这个文件，里面是有这段代码的。你的版本跟官网新版有很大区别，不知能否解决一下。

**Comment by gjTool** [comment]
你确定是用的我这里的pdf.js  和pdf.worker.js吗？我这里没有那段代码是因为我删除了，所以签章是可以显示的

**Comment by gjTool** [comment]
问题解决了。电子签章不显示是因为使用了svg模式渲染pdf。pdf.js内部机制问题。改成canvas模式渲染就可以看到电子签章了。所以今天更新了一下，增加渲染模式选择配置参数renderType:"canvas"

**Comment by xdw898618984** [comment]
> 问题解决了。电子签章不显示是因为使用了svg模式渲染pdf。pdf.js内部机制问题。改成画布模式渲染就可以看到电子签章了。所以今天更新了一下，增加渲染模式选择配置参数renderType：“画布”



> 问题解决了。电子签章不显示是因为使用了svg模式渲染pdf。pdf.js内部机制问题。改成canvas模式渲染就可以看到电子签章了。所以今天更新了一下，增加渲染模式选择配置参数renderType:"canvas"
可以说一下在哪里添加renderType:canvas 吗
