### ISSUE TITLE
这个手势缩放不是调用的pdfjs的缩放吧

### ISSUE THREAD

**Issue by gsh434541340** [gjTool/pdfh5#21]
![image](https://user-images.githubusercontent.com/11783376/62193670-cf956f00-b3aa-11e9-8174-2ca9475a095a.png)

对比了一下手势缩放和直接点击加减号缩放的清晰度不一样

**Comment by gjTool** [comment]
不是调用的pdfjs的缩放。是放大了dom，采用的css3的scale属性。源码是没有压缩，你可以研究下，或许你可以尝试调用pdfjs的缩放

**Comment by gsh434541340** [comment]
好吧
