### ISSUE TITLE
import引入报错‘fs in ./~/pdfh5/js/pdf.js’

### ISSUE THREAD

**Issue by MySecret** [gjTool/pdfh5#23]

**Comment by gjTool** [comment]
刚刚测试了一下，并没有问题，请仔细检查代码，按本插件的readme教程走

**Comment by MySecret** [comment]
> 刚刚测试了一下，并没有问题，请仔细检查代码，按本插件的readme教程走

`npm install pdfh5`之后会在**node_modules**生成三个文件夹，一个**fs**,一个**node-ensure**和一个**pdfh5**
当` import Pdfh5 from "pdfh5" `;报错：

> This dependency was not found:
> *fs in ./~/pdfh5/js/pdf.js
> to install it,you can run:npm install --save fs

`fs`应该是node的包吧，你这里pdf.js里面为什么要require('fs')，在浏览器里面肯定会报错的！

**Comment by gjTool** [comment]
> > 刚刚测试了一下，并没有问题，请仔细检查代码，按本插件的readme教程走
> 
> `npm install pdfh5`之后会在**node_modules**生成三个文件夹，一个**fs**,一个**node-ensure**和一个**pdfh5**
> 当`import Pdfh5 from "pdfh5"`;报错：
> 
> > This dependency was not found:
> > *fs in ./~/pdfh5/js/pdf.js
> > to install it,you can run:npm install --save fs
> 
> `fs`应该是node的包吧，你这里pdf.js里面为什么要require('fs')，在浏览器里面肯定会报错的！

我测试了没有你说的这个问题。我也没有引用fs。你看看本项目的example里的pdf-vue，里面是npm install pdfh5的示例

**Comment by MySecret** [comment]
> 刚刚测试了一下，并没有问题，请仔细检查代码，按本插件的readme教程走

你可以看下你的package.json,"dependencies"里面确实依赖了"fs",在** pdf.js **文件的17698行，` var fs = require('fs') ` ,而这个'fs'包压根就没有，npm install pdfh5后生成了一个'fs'目录，但是里面就一个README.md和package.json文件，压根就是一个空包。

**Comment by gjTool** [comment]
> > 刚刚测试了一下，并没有问题，请仔细检查代码，按本插件的readme教程走
> 
> 你可以看下你的package.json,"dependencies"里面确实依赖了"fs",在 **pdf.js** 文件的17698行，`var fs = require('fs')` ,而这个'fs'包压根就没有，npm install pdfh5后生成了一个'fs'目录，但是里面就一个README.md和package.json文件，压根就是一个空包。

首先你要弄清楚，pdf.js不是我写的，我只是拿来用。pdf.js是火狐浏览器团队写的。pdf.js里面用了什么我不可能去改，也不用去管。其次，我测试过了，npm install pdfh5方式没有问题。运行的很正常

**Comment by MySecret** [comment]
> > > 刚刚测试了一下，并没有问题，请仔细检查代码，按本插件的readme教程走
> > 
> > 
> > 你可以看下你的package.json,"dependencies"里面确实依赖了"fs",在 **pdf.js** 文件的17698行，`var fs = require('fs')` ,而这个'fs'包压根就没有，npm install pdfh5后生成了一个'fs'目录，但是里面就一个README.md和package.json文件，压根就是一个空包。
> 
> 首先你要弄清楚，pdf.js不是我写的，我只是拿来用。pdf.js是火狐浏览器团队写的。pdf.js里面用了什么我不可能去改，也不用去管。其次，我测试过了，npm install pdfh5方式没有问题。运行的很正常

你新建个空的文件夹，然后cd进去，打开命令行，直接运行一下`npm install pdfh5 `，看看是不是生成了3个目录，一个fs,一个node-ensure和一个pdfh5,我把这三个目录拷贝到我的mode_modules目录下，然后import Pdfh5 from "pdfh5" 就会报错。。。。方便的话可以加个微信，我拍照给你看。。wx:13814615000

**Comment by gjTool** [comment]
![image](https://user-images.githubusercontent.com/36074298/62405521-f9c87600-b5d0-11e9-89d4-b71da00abbd3.png)
我知道你说的是这个玩意。但是fs我并没有用到，这是npm包创建
都会有这个fs的。请clone本项目到本地，然后去example的pdfh5-vue去npm install 然后npm run dev。还有问题再来提issue

**Comment by gjTool** [comment]
你这么执着这个fs，我去把它去掉算了

**Comment by MySecret** [comment]
> ![image](https://user-images.githubusercontent.com/36074298/62405521-f9c87600-b5d0-11e9-89d4-b71da00abbd3.png)
> 我知道你说的是这个玩意。但是fs我并没有用到，这是npm包创建
> 都会有这个fs的。请clone本项目到本地，然后去example的pdfh5-vue去npm install 然后npm run dev。还有问题再来提issue

就是这个玩意，你把npm install下来的三个目录拷贝到vue项目中，你在`import Pdfh5 from "pdfh5"`,你会发现报错，说这个fs找不到，我发现是你的pdf.js里面`require('fs')`了，虽然pdf.js不是你写的，但是pdfh5.js应该是你写的吧。。。里面第6行`require('./pdf.js');`引用了pdf.js，而pdf.js里面的17698行，var fs = require('fs')，就会报错。

**Comment by MySecret** [comment]
> 你这么执着这个fs，我去把它去掉算了

是这样的，按照你的那个readme教程走，你会发现用不了。。。感谢您帮我解决这个问题。因为如果不能Import我就只能在html里面用script标签引入了。。。很尴尬

**Comment by MySecret** [comment]
> 你这么执着这个fs，我去把它去掉算了

你自己试一下，通过npm install pdfh5拉下来的包，能否import使用。。。。我这边用不了

**Comment by gjTool** [comment]
![image](https://user-images.githubusercontent.com/36074298/62405725-7c523500-b5d3-11e9-8381-53c605267063.png)
头皮发麻，说了没有问题，让你去下example你就是不去呢

**Comment by MySecret** [comment]
> ![image](https://user-images.githubusercontent.com/36074298/62405725-7c523500-b5d3-11e9-8381-53c605267063.png)
> 头皮发麻，说了没有问题，让你去下example你就是不去呢

我现在打算去了。。。我意思你要改一下你的那个readme，如果按照下面两步肯定是用不了的。。。我提一下，以免后面的人也遇到我这种问题。。。望改一下~~
1.安装
`npm install pdfh5`
2.使用
```
<template>
  <div id="app">
	  <div id="demo"></div>
  </div>
</template>
<script>
  import Pdfh5 from "pdfh5";
  export default {
    name: 'App',
	data() {
	  return {
	    pdfh5: null
	  };
	},
	mounted() {
	  this.pdfh5 = new Pdfh5("#demo", {
		pdfurl: "./test.pdf" 
	  });
	  this.pdfh5.on("complete", function (status, msg, time) {
		console.log("状态：" + status + "，信息：" + msg + "，耗时：" + time + "毫秒，总页数：" + this.totalNum)
	  })
	}
  }
</script>

<style>
	@import "pdfh5/css/pdfh5.css";
	*{
		padding: 0;
		margin: 0;
	}
	html,body,#app {
		width: 100%;
		height: 100%;
	}
</style>
```

**Comment by gjTool** [comment]
你说说看这个哪里有问题？

**Comment by MySecret** [comment]
> 你说说看这个哪里有问题？

你稍等，我去git上push一个demo，然后你clone下来，看看运行起来是否会报错
