### ISSUE TITLE
import pdfh5问题

### ISSUE THREAD

**Issue by MySecret** [gjTool/pdfh5#24]
[git网页](https://github.com/MySecret/pdfh5)
git克隆地址：git@github.com:MySecret/pdfh5.git

你把项目clone下来，然后`npm run dev`，看看是不是跟我一样遇到报错了。。。

**Comment by gjTool** [comment]
![image](https://user-images.githubusercontent.com/36074298/62406709-95161700-b5e2-11e9-8bce-5d55e5af9e2b.png)
我下你的demo确实报错。但是，我自己重新创建一个vue项目却没有问题。所以，抱歉，我解决不了你的问题。要不你还是换个插件吧

**Comment by MySecret** [comment]
> ![image](https://user-images.githubusercontent.com/36074298/62406709-95161700-b5e2-11e9-8bce-5d55e5af9e2b.png)
> 我下你的demo确实报错。但是，我自己重新创建一个vue项目却没有问题。所以，抱歉，我解决不了你的问题。要不你还是换个插件吧

哈哈，我想说的是，我说的是真的吧。。。。确实有问题，我相信你能解决的。。我刚刚试了下，把pdf.js里面的17698行的`var fs = require('fs')`注释掉，貌似就可以了。。。你可以试试，我希望你能和我一起研究下到底是什么原因导致的，感觉是切换到了node环境，但是我在webpack配置里面没有找到target:'node'，好奇怪。。。不过说真的，你的这个插件很棒。。。。

**Comment by MySecret** [comment]
> ![image](https://user-images.githubusercontent.com/36074298/62406709-95161700-b5e2-11e9-8bce-5d55e5af9e2b.png)
> 我下你的demo确实报错。但是，我自己重新创建一个vue项目却没有问题。所以，抱歉，我解决不了你的问题。要不你还是换个插件吧

如果你找到原因了，一定要告诉我。。。我总感觉用script标签引入比import引入low多了，而且我把pdf阅读功能抽出来做了一个component,在component里面也不好插入script，只能用到这个component的时候，在父页面把你的pdfh5所有js用script引入。。。真尴尬

**Comment by gjTool** [comment]
问题解决了，看置顶issue

**Comment by MySecret** [comment]
> 问题解决了，看置顶issue。
> 经过比对，发现你的demo里的webpack相关的配置文件和正常的vue创建的项目里的webpack配置文件差异过大。缺失很多东西，导致出现这种问题。还会出现@import "pdfh5/css/pdfh5.css";引入报错的问题。我实在不想去百度解决了，你自己去解决吧。跟插件无关，是你的webpack配置文件被你改出问题了。

我想应该也是的，但是不知道为什么会这样。。。哈哈。
