### ISSUE TITLE
出现 * fs in ./~/pdfh5/js/pdf.js 的报错看这里

### ISSUE THREAD

**Issue by gjTool** [gjTool/pdfh5#25]
![image](https://user-images.githubusercontent.com/36074298/62407502-16be7280-b5ec-11e9-8e41-9f1e85985a25.png)
使用npm install pdfh5方式的时候，有的人会出现以上报错。大体意思pdf.js引用了fs包，但是又没有找到该依赖包。按提示npm install fs也没用，因为去node_modules里找到fs你会发现fs是个空包。
产生这种错误原因具体不知道。因为我创建vue项目的时候并不会出现这个问题。
解决办法：
![image](https://user-images.githubusercontent.com/36074298/62407484-d3fc9a80-b5eb-11e9-9a3c-9b5a568a2ad3.png)
就是去webpack.dev.conf.js去修改node，在里面添加一个fs:"empty"。没有node就添加一个node,在node里添加fs:"empty"。

**Comment by gjTool** [comment]
如果还是无效，就再添加多几条
![image](https://user-images.githubusercontent.com/36074298/62407601-83863c80-b5ed-11e9-9e70-5102a0d3b553.png)
`node: {
    setImmediate: false,
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty'
  }`

**Comment by MySecret** [comment]
> 如果还是无效，就再添加多几条
> ![image](https://user-images.githubusercontent.com/36074298/62407601-83863c80-b5ed-11e9-9e70-5102a0d3b553.png)
> 
> ```
> node: {
>     setImmediate: false,
>     dgram: 'empty',
>     fs: 'empty',
>     net: 'empty',
>     tls: 'empty',
>     child_process: 'empty'
>   }
> ```

我把你的仓库clone下来，并且切换到/example/pdfh5-vue目录，然后cnpm install,将webpack.base.conf.js的node属性删掉，npm run dev后也报了 `fs in ./node_modules/_pdfh5@1.2.4@pdfh5/js/pdf.js` 可能不是我的webpack配置问题了。。。你的实例项目在我电脑上也出现了这个问题。。。尴尬

**Comment by gjTool** [comment]
？？？
大兄弟，人家vue-cli脚手架生成的webpack配置好好的，你为什么要删掉？？？你问你删掉这些配置是有什么非删不可的理由吗？

**Comment by MySecret** [comment]
> ？？？
> 大兄弟，人家vue-cli脚手架生成的webpack配置好好的，你为什么要删掉？？？请问你删掉这些配置是有什么非删不可的理由吗？

好的吧。。。哈哈。这不是看看啥原因导致的嘛。。。

**Comment by gjTool** [comment]
> > ？？？
> > 大兄弟，人家vue-cli脚手架生成的webpack配置好好的，你为什么要删掉？？？请问你删掉这些配置是有什么非删不可的理由吗？
> 
> 好的吧。。。哈哈。这不是看看啥原因导致的嘛。。。

原因这不是明摆着你把基础配置删掉了

**Comment by mismeng** [comment]
这个在nuxt的项目中该如何配置呢

**Comment by carior** [comment]
> 这个在nuxt的项目中该如何配置呢

extend(config,ctx){
　　config.node = {
　　　　fs:"empty"
　　}
}
