### ISSUE TITLE
@import "pdfh5/css/pdfh5.css" 方式引入css出错

### ISSUE THREAD

**Issue by gjTool** [gjTool/pdfh5#26]
![image](https://user-images.githubusercontent.com/36074298/62407943-107fc480-b5f3-11e9-9932-daeac2725c0a.png)
出现以上错误，可以按下图解决，将引入css代码放在script里去
![image](https://user-images.githubusercontent.com/36074298/62407955-49b83480-b5f3-11e9-8d9b-600ac9c9e72c.png)

**Comment by gjTool** [comment]
如果上述方式不能解决问题，请按需引入对应loader依赖包：
css-loader、style-loader、stylus-loader、less、less-loader、sass-loader、node-sass 
还需到webpack.base.conf.js的rules里面添加配置，具体配置请百度。

**Comment by NDCFL** [comment]
状态：error，信息：Invalid PDF structure，耗时：90毫秒，总页数：null

**Comment by dingminghui** [comment]
弄完报错更奇怪了，我就直接引入css文件了，反正效果一样
