### ISSUE TITLE
屏幕旋转后，比例会变形

### ISSUE THREAD

**Issue by wuweikd** [gjTool/pdfh5#27]
1、当屏幕旋转后，长宽比例会发生变化，导致变形，有什么解决办法吗。
2、还有一个问题，pdfh5.js源码中：部分方法中的flag并没有定义（可能是笔误）：`if (arr && arr instanceof Array) {
                for (var i = 0; i < arr.length; i++) {
                    arr[i] && arr[i].call(this, flag)
                }
            }`

**Comment by gjTool** [comment]
第二个问题是不仔细的问题。不过这两个基本无用。很好改过来。
第一个问题需要研究一下。目前你最好是锁定屏幕不让旋转

**Comment by gjTool** [comment]
问题修复了，你更新下文件

**Comment by wuweikd** [comment]
刚刚更新了你的文件，已经有效果了，非常感谢！
但是：
`window.orientationChange = function(){
        pdfh5.reset()
    }`
不需调用reset()方法，也能成功不变形；
很多设备没有onorientationchange事件，这样写更靠谱：
`
var evt = "onorientationchange" in window ? "orientationchange" : "resize";
    window.addEventListener(evt,resize,false);
    function resize() {
        pdfh5.reset()
    }`

再次感谢

**Comment by gjTool** [comment]
我只是例子测试。不写这个屏幕旋转监听也可以不变形了
