### ISSUE TITLE
pdf文件中二维码显示模糊

### ISSUE THREAD

**Issue by Pankzou** [gjTool/pdfh5#3]
我的pdf文件中有个二维码，文字都能正常显示，二维码显示模糊，代码我仅使用了初始化代码
` var pdfh5 = new Pdfh5('.pdfjs', {
                    pdfurl: 'http://cheetah.nat300.top/pdf/123.pdf'
                });`

**Comment by gjTool** [comment]
> 我的pdf文件中有个二维码，文字都能正常显示，二维码显示模糊，代码我仅使用了初始化代码
> ` var pdfh5 = new Pdfh5('.pdfjs', { pdfurl: 'http://cheetah.nat300.top/pdf/123.pdf' });`

pdf地址跨域了，我这里测不了
