### ISSUE TITLE
pdf文档，使用Acrobat设置表单域，使用iText5填充表单内容后，中文字符无法预览

### ISSUE THREAD

**Issue by wjwisme** [gjTool/pdfh5#33]
### pdf文档，使用Acrobat设置表单域，使用iText5填充表单内容后，中文无法预览

pdf文档，有些地方需要动态填充，在需要动态填充的地方使用Acrobat设置表单域后，使用java的iText5进行填充，填充后使用pdfh5预览，英文和数字显示，中文不显示，其他地方预览，都显示

### 期待的结果

中文也可以正常预览

### 截屏或录像
![1](https://user-images.githubusercontent.com/54011644/65843102-73c37400-e362-11e9-96c3-a7d91484b63e.png)

上图使用pdfh5预览，地址中是中文，不显示
![image](https://user-images.githubusercontent.com/54011644/65843135-88a00780-e362-11e9-94b9-640be1748f7d.png)
上图是在谷歌浏览器直接预览

我使用pdf.js可以预览中文

以下是我测试的前端代码：

` var pdfh5 = new Pdfh5('#demo', {
		 renderType:"canvas",
            pdfurl: "http://192.168.0.101:8080/sign/resource/upload/33302eb1-83e0-4de2-97c9-11c7565d8d27.pdf"
			 
        });`

**Comment by gjTool** [comment]
有控制台报错信息吗

**Comment by wjwisme** [comment]
我F12调试前端，没有红色错误了，使用Acrobat设置表单域刚开始我选择默认字体，数字和中文都不显示，我怀疑是字体不支持，最后选择的宋体，就出现了上面我描述的 数字显示 中文不显示的问题

**Comment by wjwisme** [comment]
> 有控制台报错信息吗

我F12调试前端，没有红色错误了，使用Acrobat设置表单域刚开始我选择默认字体，数字和中文都不显示，我怀疑是字体不支持，最后选择的宋体，就出现了上面我描述的 数字显示 中文不显示的问题

**Comment by gjTool** [comment]
这个估计要pdf.js支持才行，pdf.js不支持的话，我这个插件也支持不了

**Comment by benwk** [comment]
> > 有控制台报错信息吗
> 
> 我F12调试前端，没有红色错误了，使用Acrobat设置表单域刚开始我选择默认字体，数字和中文都不显示，我怀疑是字体不支持，最后选择的宋体，就出现了上面我描述的 数字显示 中文不显示的问题

同样的状况，加上 cMapUrl 就好了，我们用的 CDN ：

`https://unpkg.com/pdfjs-dist@2.0.943/cmaps/`
