### ISSUE TITLE
pdf加了水印 读不了

### ISSUE THREAD

**Issue by 498728659** [gjTool/pdfh5#38]
### 描述问题

Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at n.executeOpTree (pdf.js:9)
    at pdf.js:9
  pdf 可以单独打开显示正常的
### 重现步骤

后台返回的pdf加了水印后，报上面的错

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by gjTool** [comment]
https://github.com/gjTool/pdfh5/issues/33#issuecomment-567504966
参考上面的情况
