### ISSUE TITLE
android端第一次进入显示的，返回上个一层再进去就不显示了

### ISSUE THREAD

**Issue by lwk865543773** [gjTool/pdfh5#39]
### 描述问题
android端第一次进入详情界面，点击档案显示pdf的那个界面（档案界面里面有pdf插件），然后返回上个一层（详情界面），再点击档案再进去就不显示了（空白一片，但日志台上是没问题的）；（都是在android的webview中）
但android把webview的这个activity关掉后，在第一次进入就没问题的；

### 移动端环境

- Device: android手机
- OS: android系统8.0  全部android手机都不行
- Browser 都在android的webview中
- Version 1.2.22

请提供其他附加信息帮助我们诊断问题。

**Comment by gjTool** [comment]
请仔细检查代码，或者提供代码详情/错误截图
