### ISSUE TITLE
阅读很多文档后容易乱，canvas画不过来么

### ISSUE THREAD

**Issue by hu-gu-yue** [gjTool/pdfh5#4]
加载很多文档后，手机容易出现死机 卡顿

**Comment by gjTool** [comment]
> 加载很多文档后，手机容易出现死机 卡顿

如果频繁的去加载pdf，例如，加载一个pdf，然后返回，在去加载另外一个pdf。这样的话，需要在返回的时候调用destroy方法

**Comment by hu-gu-yue** [comment]
感谢您的回复！
另外还有一个问题，只要PDF一长，下拉速度太快，就容易导致图像倒了，卡顿，或者画不出来为空白，黑板，然后之后就一直画不出了，退出也没用，只有清除缓存才可以，有没有什么思路给我，我来改改

**Comment by gjTool** [comment]
> 感谢您的回复！
> 另外还有一个问题，只要PDF一长，下拉速度太快，就容易导致图像倒了，卡顿，或者画不出来为空白，黑板，然后之后就一直画不出了，退出也没用，只有清除缓存才可以，有没有什么思路给我，我来改改

pdfh5.js插件是解析pdf后，一页一页的画canvas，所以pdf过长肯定会导致你说的情况。目前建议是在pdf未加载完成禁止滚动页面。你可能用到两个方法pdfh5.start、 pdfh5.complete。用法：pdfh5.complete(function(){})

**Comment by hu-gu-yue** [comment]
您的意思是整个PDF文档加载完成再开始画吗

**Comment by gjTool** [comment]
> 您的意思是整个PDF文档加载完成再开始画吗

你自己解析pdf画canvas？没懂你的意思

**Comment by hu-gu-yue** [comment]
没有呀 ，用你的PDFh5来做，我就是想解决滑动太快，画不出来的问题，我看你的源码也判断了是否加载PDF完成，你上一条说的意思我没太明白，在哪里使用pdfh5.complete  和 start  是否可以写一点伪代码...

**Comment by gjTool** [comment]
例如，页面一进来就设置页面或者pdf的容器不能滚动。然后初始化过后，在pdfh5.complete(function(){})里面允许滚动

**Comment by hu-gu-yue** [comment]
这样的话会影响用户体验。我看你的代码也是一页一页画的，能不能在【加载下一页】那个逻辑判断是否PDF这一页加载完成

**Comment by gjTool** [comment]
昨天更新。on监听各种事件。renderPages监听当前加载pdf页数，	currentPageDom当前pdf页的dom,	currentNum当前的pdf页码
pdfh5.on("renderPages",function(currentPageDom){
			console.log(currentPageDom)
			console.log(pdfh5.currentNum)
		})
你要别的你自己去改吧，源码也不多

**Comment by gjTool** [comment]
> 这样的话会影响用户体验。我看你的代码也是一页一页画的，能不能在【加载下一页】那个逻辑判断是否PDF这一页加载完成

目前没有时间去优化。以后空下来了再优化吧。写这插件的初衷是一个项目用到了
