### ISSUE TITLE
当pdf图片很多几百张的时候，滑到一定数量会卡并且个别pdf不会渲染，一直loading效果

### ISSUE THREAD

**Issue by qqis314860100** [gjTool/pdfh5#42]
当pdf图片很多几百张的时候，滑到一定数量会卡并且个别pdf不会渲染，一直loading效果

**Comment by gjTool** [comment]
这个没办法，h5性能现在只能这样，比较依赖浏览器，webview，以后可能会好些吧。所以h5只能预览小的，真要预览大的最好是下载下来看，或者用原生插件预览
