### ISSUE TITLE
pdf只能显示第一页，后续页面一直loading

### ISSUE THREAD

**Issue by 17521123951** [gjTool/pdfh5#43]
`###` 描述问题

在线预览pdf只能显示第一页

### 重现步骤

请描述如何重现这个问题：

pdf获取总页数为6，但是渲染第一页过后就停止渲染，没有触发complete事件

### 期待的结果

能正常显示6页数据

### 截屏或录像

我的js配置如下：
var pdfh5 = new Pdfh5('#handout_wrap_inner', {
                pdfurl: '/' + contract,
                renderType : 'canvas',
                maxZoom : 1,
                loadingBar : false,
                lazy : true,
                cMapUrl : '/js/plugins/pdfjs/cmaps/',
            });

浏览器控制台输出如下：
![image](https://user-images.githubusercontent.com/61185492/74725152-7888b600-5278-11ea-85af-bec043985475.png)

### 桌面端环境

- OS: [mac]
- Browser [chrome]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by gjTool** [comment]
lazy : true,改成lazy : fasle
