### ISSUE TITLE
数字证书的显示问题和小程序的兼容问题

### ISSUE THREAD

**Issue by zhoubo93** [gjTool/pdfh5#45]
1、svg渲染模式的情况下签名、数字证书都无法显示。
2、小程序显示的时候因为我不是全屏显示，header+main，出现了只显示单页的纸张长度，不能占满，尤其是FDA表格。

**Comment by rourkesu2015** [comment]
有解决吗 遇到类似的问题了

**Comment by zhoubo93** [comment]
> 有解决吗 遇到类似的问题了

启用canvas模式就可以预览签章和数字签名了

**Comment by rourkesu2015** [comment]
但是个别文件还是会文字错乱 不显示 加载不出的问题&nbsp; 就是原PDF文件的一页 好多图层&nbsp; 在手机端就会出现




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhoubo93"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 晚上6:11
收件人:&nbsp;"gjTool/pdfh5"<pdfh5@noreply.github.com&gt;;
抄送:&nbsp;"翡翠白玉汤"<572525999@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [gjTool/pdfh5] 数字证书的显示问题和小程序的兼容问题 (#45)





  
有解决吗 遇到类似的问题了
  
启用canvas模式就可以预览签章和数字签名了

**Comment by zhoubo93** [comment]
感觉canvas的渲染效果不太好，虽然在模拟器中看起来还行，但是在手机上体验很糟糕。经常会出现滑不动的情况，以及没法缩小适应屏幕的大小。所以我又换回了svg的方式。期待作者能够解决一下这个问题。



---原始邮件---
发件人: "rourkesu2015"<notifications@github.com&gt;
发送时间: 2020年4月22日(周三) 晚上6:57
收件人: "gjTool/pdfh5"<pdfh5@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"zhoubo93"<1826992383@qq.com&gt;;
主题: Re: [gjTool/pdfh5] 数字证书的显示问题和小程序的兼容问题 (#45)




 但是个别文件还是会文字错乱 不显示 加载不出的问题&amp;nbsp; 就是原PDF文件的一页 好多图层&amp;nbsp; 在手机端就会出现 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"zhoubo93"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年4月22日(星期三) 晚上6:11 
 收件人:&amp;nbsp;"gjTool/pdfh5"<pdfh5@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"翡翠白玉汤"<572525999@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [gjTool/pdfh5] 数字证书的显示问题和小程序的兼容问题 (#45) 
 
 
 
 
 
    
 有解决吗 遇到类似的问题了 
    
 启用canvas模式就可以预览签章和数字签名了

**Comment by rourkesu2015** [comment]
是的 手机体验确实很糟糕&nbsp; 哎。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhoubo93"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 晚上7:07
收件人:&nbsp;"gjTool/pdfh5"<pdfh5@noreply.github.com&gt;;
抄送:&nbsp;"翡翠白玉汤"<572525999@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [gjTool/pdfh5] 数字证书的显示问题和小程序的兼容问题 (#45)





 感觉canvas的渲染效果不太好，虽然在模拟器中看起来还行，但是在手机上体验很糟糕。经常会出现滑不动的情况，以及没法缩小适应屏幕的大小。所以我又换回了svg的方式。期待作者能够解决一下这个问题。 
 
 
 
 ---原始邮件--- 
 发件人: "rourkesu2015"<notifications@github.com&amp;gt; 
 发送时间: 2020年4月22日(周三) 晚上6:57 
 收件人: "gjTool/pdfh5"<pdfh5@noreply.github.com&amp;gt;; 
 抄送: "State change"<state_change@noreply.github.com&amp;gt;;"zhoubo93"<1826992383@qq.com&amp;gt;; 
 主题: Re: [gjTool/pdfh5] 数字证书的显示问题和小程序的兼容问题 (#45) 
 
 
 
 
  但是个别文件还是会文字错乱 不显示 加载不出的问题&amp;amp;nbsp; 就是原PDF文件的一页 好多图层&amp;amp;nbsp; 在手机端就会出现  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"zhoubo93"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年4月22日(星期三) 晚上6:11  
  收件人:&amp;amp;nbsp;"gjTool/pdfh5"<pdfh5@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"翡翠白玉汤"<572525999@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [gjTool/pdfh5] 数字证书的显示问题和小程序的兼容问题 (#45)  
   
   
   
   
   
      
  有解决吗 遇到类似的问题了  
      
  启用canvas模式就可以预览签章和数字签名了
