### ISSUE TITLE
发票显示不全问题

### ISSUE THREAD

**Issue by lizhizhi186** [gjTool/pdfh5#47]
图一是pdf原图 ，第二是展示之后的图片，显示不全
[qianzhang.pdf](https://github.com/gjTool/pdfh5/files/4352425/qianzhang.pdf)
![FE7958D003C4D196FD265B78EC24973E](https://user-images.githubusercontent.com/32266721/77026646-20f07e00-69cf-11ea-901f-88bad32c6f1c.png)

### 你在什么场景下需要该功能？

请尽量清晰精准地描述你碰到的问题。

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by C-gavin** [comment]
可能是因为发票字体问题，楼主把cMapUrl加上，写法如下：
            let pdfh5 = new Pdfh5('#wrap', {
                pdfurl:this.FileUrl,
                cMapUrl:"https://unpkg.com/pdfjs-dist@2.0.943/cmaps/",
            });

**Comment by kevinYSwei** [comment]
请问加上https://unpkg.com/pdfjs-dist@2.0.943/cmaps/之后 有的logo图片在手机端还是展示不全，而且有的字体重叠在一起了 该怎么解决？

**Comment by gjTool** [comment]
默认是svg渲染，svg渲染有很多问题。现在最新版本默认canvas渲染没有该问题
