### ISSUE TITLE
 加载本地pdf报错

### ISSUE THREAD

**Issue by guofeifeifei** [gjTool/pdfh5#5]
pdf.js:9 Fetch API cannot load file:///Users/11/Downloads/pdfh5-master/default.pdf. URL scheme must be "http" or "https" for CORS request.
e @ pdf.js:9

**Comment by gjTool** [comment]
> pdf.js:9 Fetch API cannot load file:///Users/11/Downloads/pdfh5-master/default.pdf. URL scheme must be "http" or "https" for CORS request.
> e @ pdf.js:9

必须要服务启动。http或者https

**Comment by guofeifeifei** [comment]
但是我加载的是本地pdf

**Comment by gjTool** [comment]
> 但是我加载的是本地pdf

跟你加载什么本地pdf没关系，看报错就知道了，是你没有用服务把插件打开。给你举个例子，用hbuilder打开html，然后在里面用谷歌浏览器运行，浏览器地址栏会出现http://127.0.0.1:8020/xxx.html  ,这就是服务启动。

**Comment by gjTool** [comment]
> 但是我加载的是本地pdf

最好用相对地址，或者http开头的地址，不要用file开头的。js的规则是不允许操作本地文件。所以对file开头的东西不可控
