### ISSUE TITLE
参数lazy设置为true后，loadingBar:false失效，拖动视图会触发loadingBar消失

### ISSUE THREAD

**Issue by zgx33** [gjTool/pdfh5#51]
### 描述问题

参数lazy设置为true后，loadingBar:false失效，拖动视图会触发loadingBar消失

### 重现步骤

请描述如何重现这个问题：

1. 加载网络pdf 设置为lazy模式
2. 进入loading 一直在转
3. 拖动视图会触发loadingBar消失，否则会一直存在

### 期待的结果

参数lazy设置为true后，加载当前可视图的pdf的loadingBar 消失

**Comment by gjTool** [comment]
已修复
