### ISSUE TITLE
pdf文件里面的表格 安卓显示黑块 IOS无问题 pc无问题

### ISSUE THREAD

**Issue by rourkesu2015** [gjTool/pdfh5#52]
### 描述问题

展示pdf文件里面的表格 安卓显示黑块 IOS无问题 pc无问题

### 重现步骤

请描述如何重现这个问题：

直接打开就有此问题

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像
![black](https://user-images.githubusercontent.com/20575389/78654526-36ced000-78f7-11ea-8b75-798790cfdae4.jpg)
![normal](https://user-images.githubusercontent.com/20575389/78654528-39312a00-78f7-11ea-9963-728d8f90ce3b.png)

]

### 桌面端环境

- OS: [e.g. windows,]
- Browser [e.g. chrome,]

### 移动端环境

- Device: [e.g. iPhone10,华为, 三星，小米

- OS: [e.g. iOS12，e.g.andriod9.0,e.g.andriod9.0 ]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by gjTool** [comment]
请附上代码➕机型
