### ISSUE TITLE
如果能够识别文档上的网址，打开链接，就更好了 。如果可以，请联系我微信8777817 长沙香樟路

### ISSUE THREAD

**Issue by zwdwww** [gjTool/pdfh5#53]
### 如果可以，请联系我微信8777817 长沙香樟路
你在什么场景下需要该功能？

请尽量清晰精准地描述你碰到的问题。

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by gjTool** [comment]
后续会加上，计划在6月份，5月份先优化插件，复制文本以及跳转链接放在后面计划

**Comment by Zhaiaiguo518** [comment]
> 

请问这个加上了吗？
