### ISSUE TITLE
lazy与disabeRange

### ISSUE THREAD

**Issue by wideweide** [gjTool/pdfh5#54]
请教一下lazy是指什么？与pdf.js的disabeRange有何差异？

另外请教一下：看pdf.js的官网示例，disabeRange默认false，第一次请求的时候返回200，大小为0，
但pdfh5默认返回200，仍然下载了整个文件，后续又分块下载了一些文件，这是什么原因？

以及如果java sevlet如何实现一个download接口支持disableRange=false时的分块下载？

**Comment by gjTool** [comment]
不清楚disabeRange是什么。本插件不支持分块下载。后续下载的文件其实不是下载，只是渲染pdf加载的图片
