### ISSUE TITLE
数字证书无法在svg模式下显示，但是在canvas模式下整个页面渲染表现很糟糕，无法适配手机屏幕，滑动下一页跟放大缩小有冲突

### ISSUE THREAD

**Issue by zhoubo93** [gjTool/pdfh5#56]
### 描述问题

请尽量清晰精准地描述你碰到的问题。

### 重现步骤

请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by gjTool** [comment]
正在优化了
