### ISSUE TITLE
跨域

### ISSUE THREAD

**Issue by xuyuchenfei** [gjTool/pdfh5#6]
跨域问题怎么解决

**Comment by gjTool** [comment]
跨域不是插件的问题。跨域要后端配合才行。纯前端跨不了域。你百度一下跨域吧

**Comment by cowboy1997** [comment]
我们是直接把文件和插件放在一个服务器文件夹，然后在iframe里直接加载这个网域的文件，这样就相当于自己访问自己，就不存在跨域了
