### ISSUE TITLE
有什么方法添加水印不影响手势缩放功能吗

### ISSUE THREAD

**Issue by Meatchell** [gjTool/pdfh5#60]
### 你在什么场景下需要该功能？

请尽量清晰精准地描述你碰到的问题。

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by gjTool** [comment]
暂时没有该功能。添加水印已列入后续版本计划中

**Comment by gjTool** [comment]
水印方法已添加
