### ISSUE TITLE
在移动端，进度条100%了，但是所有page还都是显示loading，多次查看还会造成app闪退

### ISSUE THREAD

**Issue by hxw93** [gjTool/pdfh5#61]
### 描述问题

在移动端，查看pdf,全部加载完之后，关闭页面。查看pdf，关闭再查看，重复几次之后，再查看pdf，进度条一直在变化，到最后100%消失，但是所有pdf页都还是显示loading。

### 重现步骤

请描述如何重现这个问题：
1.点击查看pdf，跳转查看页
2.加载完成后，关闭查看页
3.点击其他pdf进行查看
4.加载完成后，关闭查看页
5.重复几次，再次打开查看页，会出现进度条一直在变化，但所有pdf页一直显示loading，内容没展示出来
6. 重复多次的话，会造成app闪退

### 期待的结果

希望正常展示pdf内容，app不闪退

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 移动端环境
一直显示loading：
- OS: ios
- Browser chrome
- Version： 13.3

- Device: iphonexs
- OS: ios13.3
- Browser: chrome
- Version: 13.3

闪退：
测试机：honor note 10
- Device: honor note 10
- OS: android 9
- Browser：chrome
- Version： 9

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by gjTool** [comment]
你可以尝试关闭查看页的时候调用destroy方法

**Comment by hxw93** [comment]
一直都有在页面即将关闭的时候调用destroy方法的了。

**Comment by gjTool** [comment]
pdf的问题，pdf.js解析不行
