### ISSUE TITLE
缩放后，PDF滚动失效

### ISSUE THREAD

**Issue by q5401103q** [gjTool/pdfh5#62]
### 描述问题

加载完PDF后，使用手势缩放PDF，PDF滚动浏览失效，只能看到PDF的1-2页。

### 重现步骤

请描述如何重现这个问题：

1. 加载PDF
2. 使用手势放大PDF
3. 双击缩小PDF
4. 恢复正常浏览
5. 滚动失效

### 期待的结果

缩放不影响PDF滚动浏览

### 截屏或录像

无

### 桌面端环境

- OS: windows
- Browser : chrome
- Version : 80.0.3987.132

### 其他信息

无

**Comment by gjTool** [comment]
电脑端谷歌浏览器并不能手势缩放，我无法重现这个问题
