### ISSUE TITLE
最新版放大后会变成加载中的状态

### ISSUE THREAD

**Issue by ttjn18** [gjTool/pdfh5#63]
### 描述问题
部分pdf在移动端真机放大后会变成加载中状态, 缩小后还是一样, 使用的是最新的1.3.9版本.
之前用1.2.21版本也是这些pdf一直是加载中状态, 其他pdf没有问题. 不知道是不是pdf文件有问题?
但是在pc端是可以预览的

**Comment by gjTool** [comment]
pdf的问题。pdf.js解析不出来
