### ISSUE TITLE
loadEffect 加载完成后没有隐藏

### ISSUE THREAD

**Issue by musez** [gjTool/pdfh5#69]
### 描述问题

loadEffect 没有隐藏。pdf 加载完成后，loadEffect 没有进行隐藏。当 pdf 高度高度大于半屏时，loadEffect  会被遮盖住。当 pdf 高度小于半屏时，loadEffect  会显示出来

### 重现步骤

无

### 期待的结果

pdf 加载完成后，loadEffect 进行隐藏。

### 截屏或录像

![image](https://user-images.githubusercontent.com/14009673/86549264-b5c4ba80-bf71-11ea-8e19-bc1e379dd681.png)

### 桌面端环境

- chrome

### 移动端环境

- HUAWEI P20
- android

### 其他信息

无

**Comment by gjTool** [comment]
新版本已解决
