### ISSUE TITLE
请问能否配置PDF分段加载？对于大于100MB的PDF文件加载可能会比较慢

### ISSUE THREAD

**Issue by cowboy1997** [gjTool/pdfh5#7]
原生PDFJS有个rangeChunkSize参数可配置分段加载大小，请问这里是否也能配置PDF分段加载？对于大于100MB的PDF文件加载可能会比较慢。

**Comment by gjTool** [comment]
抱歉，当初写这个插件是给公司项目用的，并没有考虑到这个。手机端看这么大的pdf还是比较少见的。由于本插件的渲染机制问题，分段加载会跟手势缩放那里有冲突，有空我研究下吧。

**Comment by cowboy1997** [comment]
好的，谢谢！

**Comment by gjTool** [comment]
现在改成svg渲染了，你可以看看加载效果是不是好一些了
