### ISSUE TITLE
添加水印功能，使用背景图

### ISSUE THREAD

**Issue by musez** [gjTool/pdfh5#70]
### 你在什么场景下需要该功能？

插件中使用 img 标签来生成水印，局限性较大，不能进行图片的重复展示。

### 描述可能的解决方案

可以将 img 标签替换成 div ，使用背景图的形式，进行水印的展示。这样，既能进行单个，也能进行重复展示。

### 描述你认为的候选方案

无

### 其他信息

无

**Comment by gjTool** [comment]
不太能明白你的描述，请重新组织下语言

**Comment by musez** [comment]
我需要的是在整个背景上重复的添加水印，而不仅仅是添加一个logo的水印。像下图这种：
![水印](https://images2018.cnblogs.com/blog/1266852/201808/1266852-20180806212005905-96609313.png)
这种水印，使用背景图片，更容易实现一些。插件中使用 img 标签，不容易实现。

**Comment by deliveph** [comment]
新的版本能不能放开scale此功能啊 不然加载很模糊

**Comment by gjTool** [comment]
> 新的版本能不能放开scale此功能啊 不然加载很模糊

已经放开了

**Comment by deliveph** [comment]
👍

**Comment by gjTool** [comment]
> 我需要的是在整个背景上重复的添加水印，而不仅仅是添加一个logo的水印。像下图这种：
> ![水印](https://camo.githubusercontent.com/27eecc2b1160e447f562b2fcfb7f59f016ecb79b/68747470733a2f2f696d61676573323031382e636e626c6f67732e636f6d2f626c6f672f313236363835322f3230313830382f313236363835322d32303138303830363231323030353930352d39363630393331332e706e67)
> 这种水印，使用背景图片，更容易实现一些。插件中使用 img 标签，不容易实现。

v1.3.18版本已经实现背景图属性添加
