### ISSUE TITLE
现有项目中尝试使用报错

### ISSUE THREAD

**Issue by cfy2015** [gjTool/pdfh5#73]
之前使用vue-pdf发现签章会有promise的崩溃，就尝试使用这个组件
然后按照demo的使用加载流文件直接报错如下：
pdfh5.js?23f7:649 Uncaught (in promise) TypeError: Cannot read property 'pdfLoaded' of undefined
    at Pdfh5.init (pdfh5.js?23f7:649)
    at new Pdfh5 (pdfh5.js?23f7:626)
    at eval (index.vue?6ced:77)

**Comment by cfy2015** [comment]
我太蠢了。。。已经解决。。。

**Comment by OnlyFlyer** [comment]
Hi, guys, How did you solve it ?

**Comment by OnlyFlyer** [comment]
> 我太蠢了。。。已经解决。。。

```
new Pdfh5('#root', {
   pdfurl: 'my path'
   // renderType: 'svg'
})

or

new Pdfh5('.root', {
   pdfurl: 'my path'
   // renderType: 'svg'
})

```

oh, I was so stupid.
