### ISSUE TITLE
IOS 放大后会出现loading 且loading不会消失

### ISSUE THREAD

**Issue by Meatchell** [gjTool/pdfh5#74]
### 描述问题

IOS 放大后会出现loading 且loading不会消失

### 重现步骤

请描述如何重现这个问题：

一直放大
```,
      lazy:true,
      renderType: 'canvas',
      maxZoom: 5,
```

### 期待的结果
不会出现loading

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像
[http://testexpert.njdzny.cn:8019/interface/UploadFile/2020-07-08/85807034474160582118604132120984.8/image/5bb67bee-bbf7-4ce2-a2f8-df1bfe4ce5fd.jpg](url)

### 出现错误PDF
[http://testexpert.njdzny.cn:8019/interface/UploadFile/2020-07-08/d301eef1-cf34-4bb8-bb50-57f3c03ed51f/PDF/28b00ea2-fec0-4198-92e4-7633a21db335.pdf](url)

### 移动端环境

- Device: [iPhone8]
- OS: [iOS12]
- Browser [ safari]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by gjTool** [comment]
新版本已解决

**Comment by Meatchell** [comment]
loading虽然消失了，但页面空白，没有内容显示
