### ISSUE TITLE
报错“pdfjsLib is not defined”是什么原因

### ISSUE THREAD

**Issue by chenheng0910** [gjTool/pdfh5#8]
![Uploading image.png…]()

**Comment by gjTool** [comment]
> ionic.bundle.js:26794 ReferenceError: pdfjsLib is not defined
> at getDoc (pdfh5.js:962)
> at Pdfh5.init (pdfh5.js:946)
> at new Pdfh5 (pdfh5.js:802)
> at TrainingPlanCtrl.js:25
> at processQueue (ionic.bundle.js:29127)
> at ionic.bundle.js:29143
> at Scope.$eval (ionic.bundle.js:30395)
> at Scope.$digest (ionic.bundle.js:30211)
> at ionic.bundle.js:30434
> at completeOutstandingRequest (ionic.bundle.js:19194)

没有引用pdf.js和pdf.worker.js

**Comment by chenheng0910** [comment]
@gjTool 已经搞定了，🙏。

**Comment by alisa-hui** [comment]
我引入了pdf.js和pdf.worker.js,但是还是报这个错误啊,是什么原因啊

**Comment by alisa-hui** [comment]
我替换后就好了,谢谢,pdf超过1M的时候,加载的会非常非常慢,请问有什么可以优化的吗?

**Comment by gjTool** [comment]
> 我替换后就好了,谢谢,pdf超过1M的时候,加载的会非常非常慢,请问有什么可以优化的吗?

这个我知道原因，一次性把所有pdf转换成流了，然后再一页一页的画canvas转成jpg/p
ng渲染出来。我目前有新的项目要忙，暂时没空思考改善这个。你可以去看源码pdfh5.js，是没有压缩的，你可以试着改进一下

**Comment by alisa-hui** [comment]
> > 我替换后就好了,谢谢,pdf超过1M的时候,加载的会非常非常慢,请问有什么可以优化的吗?
> 
> 这个我知道原因，一次性把所有pdf转换成流了，然后再一页一页的画canvas转成jpg/p
> ng渲染出来。我目前有新的项目要忙，暂时没空思考改善这个。你可以去看源码pdfh5.js，是没有压缩的，你可以试着改进一下

好的,我先看下
