### ISSUE TITLE
resize有冲突

### ISSUE THREAD

**Issue by ghostman-git** [gjTool/pdfh5#84]
跟自己的项目产生冲突报错

**Comment by ghostman-git** [comment]
resize
![image](https://user-images.githubusercontent.com/13376074/91257597-ed472a80-e79c-11ea-8841-6d833b17e170.png)
![image](https://user-images.githubusercontent.com/13376074/91257619-f637fc00-e79c-11ea-9baa-7cd40c573af3.png)

**Comment by gjTool** [comment]
我自己测试没有冲突。有问题可以加微信群问
