### ISSUE TITLE
这个插件对div容器的布局有要求吗

### ISSUE THREAD

**Issue by rsq1259** [gjTool/pdfh5#85]
想将pdf展示在页面中的某个部分，请求文件服务器中的pdf后没加载成功，class="pdfViewer"的div为空，监听complete事件获取到msg:Invalid PDF structure。
但是直接将pdf链接复制到项目所给的demo中是可以加载出来的。
所以想问下这个是不是对div容器有什么要求？

**Comment by rsq1259** [comment]
pdfjsLib.getDocument(obj)这一步一直报错

**Comment by gjTool** [comment]
加微信群问

**Comment by gjTool** [comment]
从来没有人提出来你这个报错。你一不发代码截图，二不发报错截图，你要是不愿意加群问，那就换个插件好了。这个插件不适合你
