### ISSUE TITLE
后台直接返回了pdf的文件流，请问应该怎么处理显示？

### ISSUE THREAD

**Issue by 1409004379** [gjTool/pdfh5#87]
![image](https://user-images.githubusercontent.com/26536793/93158565-eded3400-f73e-11ea-9589-a0da3c46ca8d.png)
请教群主，后端返回的这种格式的数据，我应该怎么处理显示？

**Comment by gjTool** [comment]
看文档

**Comment by SAKURA-LBY** [comment]
大佬这是要将文件流转成blob对象放在data里吗
