### ISSUE TITLE
PDF标题一行文字太多，SVG方式渲染出来标题栏文字重叠，怎么解决呢

### ISSUE THREAD

**Issue by laiyangFly** [gjTool/pdfh5#88]
![7641746A-3349-47b4-8504-B8B3FA4F77F2](https://user-images.githubusercontent.com/28632477/93553491-b46a3200-f9a5-11ea-98f3-8047a3446d9a.png)

**Comment by gjTool** [comment]
使用canvas模式，svg不建议使用
